name: render
on: push
jobs:
  render:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: fontist/setup-fontist@v2
      - run: fontist install "Fira Sans"
      - run: fontist install "Libertinus"
      - run: fontist install "Fira Code"
      
      - uses: typst-community/setup-typst@v4
      - name: Compile kmedian.typ
        run: typst compile kmedian.typ kmedian.pdf --font-path ~/.fontist/fonts
      
      - uses: actions/upload-artifact@v4
        with:
          name: kmedian
          path: kmedian.pdf
          
      - name: Get current date
        id: timestamp
        run: echo "timestamp=$(date +'%Y-%m-%d-%H.%M')" >> $GITHUB_OUTPUT
        
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${{ steps.timestamp.outputs.timestamp }}"
          gh release create "v$VERSION" \
            --title "PDFs rendered on $VERSION" \
            --notes "Rendered on $(date +'%Y-%m-%d %H:%M:%S') via [github-actions](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})." \
            kmedian.pdf