name: render
on: push
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v4
      - name: Compile all .typ files
        run: |
          for file in $(find . -name "*.typ"); do
            echo "Compiling $file"
            typst compile "$file"
          done